matrix:
  include:
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      env:
        #- NMAKE_PATH="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/"
        #- RC_PATH="/c/Program Files (x86)/Windows Kits/10/bin/x64/"
        #- PATH="/c/Python36:/c/Python36/Scripts:$NMAKE_PATH:$RC_PATH:$PATH"
        - PATH="/c/Python36:/c/Python36/Scripts:/c/Program Files (x86)/keystone/bin/:$PATH"
      before_install:
        - choco install python --version=3.6.8
        #- choco install cmake
        #- choco install visualstudio2019community
        - python -m pip install --upgrade pip
      install:
        - pip install 'capstone>=4.0.1' 'pefile>=2019.4.18' 'python-registry>=1.3.1' 'unicorn>=1.0.2rc1'
        #- pip install -r requirements.txt
        - git clone https://github.com/keystone-engine/keystone
        - cd keystone
        - mkdir build
        - cd build
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 & ..\nmake-dll.bat'
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 & ..\nmake-lib.bat && nmake install'
        #- cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 & pip install -r requirements.txt'
        - cd ../bindings/python
        - python setup.py install
        - cd $TRAVIS_HOME/build/chfl4gs/qiling
        - python setup.py install
       before_script:
        - cd tests
       script:
        - python test_all.py
   allow_failures: 
     - windows
