language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  # fix keystone lib
  - cp /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/keystone/libkeystone.so /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/keystone/
script:
  - cd tests
  - python3 shellcode_test.py
