language: shell
matrix:
  fast_finish: true
  include:   
    - name: "Windows WSL1"
      os: windows
      language: shell
      before_install:
        - choco install wsl-ubuntu-1804
        - wsl apt update
        - wsl DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y
        - wsl DEBIAN_FRONTEND=noninteractive apt install -y python3-pip cmake
        - wsl pip3 install --upgrade pip
      install:
        - wsl pip3 install -r requirements.txt
        - wsl python3 setup.py install
      before_script:
        - MSYS_NO_PATHCONV=1 wsl cp $(wsl python3 -c "import site; print(site.getsitepackages()[0])")$(wsl python3 -c "import site; print(site.getsitepackages()[1])")/keystone/libkeystone.so $(wsl python3 -c "import site; print(site.getsitepackages()[0])")/keystone/
        - cd tests
      script:
        - wsl python3 test_all.py
