matrix:
  include:
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      env:
        - PATH="/c/Python36:/c/Python36/Scripts:/c/Program Files (x86)/keystone/bin/:$PATH"
        # export PS1="[\[$(tput sgr0)\]\[\033[38;5;249m\]\t\[$(tput sgr0)\]\[\033[38;5;15m\]] \[$(tput sgr0)\]\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;202m\]@\[$(tput sgr0)\]\[\033[38;5;43m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;33m\]\w\[$(tput sgr0)\]\[\033[38;5;6m\]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;118m\]\\$\[$(tput sgr0)\]"
      before_install:
        - choco install python --version=3.6.8
        #- choco install cmake
        #- choco install visualstudio2019community
        - python -m pip install --upgrade pip
      install:
        - pip install 'capstone>=4.0.1' 'pefile>=2019.4.18' 'python-registry>=1.3.1' 'unicorn>=1.0.2rc1'
        #- pip install -r requirements.txt
        - git clone https://github.com/keystone-engine/keystone
        - cd keystone
        - mkdir build
        - cd build
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 & ..\nmake-dll.bat'
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 & ..\nmake-lib.bat && nmake install'
        - cd ../bindings/python
        - python setup.py install
        - cd $TRAVIS_HOME/build/chfl4gs/qiling
        - python setup.py install
before_script:
        - cd tests
script:
  - python test_all.py
