matrix:
  include:
    - name: "Python 3.6 on Windows"
      os: windows
      language: sh
      env:
        - PATH="/c/Python36:/c/Python36/Scripts:$PATH"
      before_install:
        - choco install python --version=3.6.8
        - choco install cmake
        - python -m pip install --upgrade pip
      install:
        - pip install 'capstone>=4.0.1' 'pefile>=2019.4.18' 'python-registry>=1.3.1' 'unicorn>=1.0.2rc1'
        - git clone https://github.com/keystone-engine/keystone
        - cd keystone && mkdir build && cd build && ../nmake-dll.bat && ../nmake-lib.bat
        - python setup.py install
      before_script:
        - cd tests
script:
  - python test_all.py
