language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  # fix keystone lib
  - cp /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/keystone/libkeystone.so /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/keystone/
script:
  - python3 ./qltool run -f examples/rootfs/x8664_linux/bin/x8664_hello --rootfs examples/rootfs/x8664_linux
  - python3 ./qltool run -f examples/rootfs/x86_linux/bin/x86_hello --rootfs examples/rootfs/x86_linux
  - python3 ./qltool run -f examples/rootfs/mips32el_linux/bin/mips32el_hello --rootfs examples/rootfs/mips32el_linux
  - python3 ./qltool run -f examples/rootfs/x86_reactos/bin/x86_hello.exe --rootfs examples/rootfs/x86_reactos
  - python3 ./qltool run -f examples/rootfs/x8664_reactos/bin/x8664_hello.exe --rootfs examples/rootfs/x8664_reactos
  - cd tests    
  - python3 test_shellcode.py
  - python3 test_elf.py
