matrix:
  include:
    - name: "Python 3.5 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
      install:
        - pip install -r requirements.txt
      before_script:
        - cd tests
      script:
        - python3 test_all.py
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      install:
        - pip install -r requirements.txt
      before_script:
        - cd tests
      script:
        - python3 test_all.py
    - name: "Python 3.5 on Linux"
      os: linux
      language: python
      python: "3.5"
      install:
        - pip3 install -r requirements.txt
      before_script:
        - pysite=$(python3 -m sysconfig | sed -n '/purelib/ s/.*\= *//p' | xargs); cp ${pysite}${pysite}/keystone/libkeystone.so $pysite/keystone/
        - cd tests
      script:
        - python3 test_all.py
    - name: "Python 3.6 on Linux"
      os: linux
      language: python
      python: "3.6"
      install:
        - pip3 install -r requirements.txt
      before_script:
        - pysite=$(python3 -m sysconfig | sed -n '/purelib/ s/.*\= *//p' | xargs); cp ${pysite}${pysite}/keystone/libkeystone.so $pysite/keystone/
        - cd tests
      script:
        - python3 test_all.py
    - name: "Python 3.7 on osx"
      os: osx
      language: shell
      install:
        - pip install --upgrade pip
        - pip install -r requirements.txt
      before_script:
        - cd tests
      script:
        - python3 test_all.py
